### ISSUE TITLE
Missing `request` dependency?

### ISSUE THREAD

**Issue by dylanpyle** [jaebradley/uber-cli#20]
node v6.4.0

```
$ npm install uber-cli -g
/Users/dylan/n/bin/uber -> /Users/dylan/n/lib/node_modules/uber-cli/build/executables/uber.js
/Users/dylan/n/lib
└─┬ uber-cli@0.0.1
  ├── @google/maps@0.3.1
  ├─┬ cli-table2@0.2.0
  │ ├── lodash@3.10.1
  │ └─┬ string-width@1.0.2
  │   ├── code-point-at@1.1.0
  │   ├─┬ is-fullwidth-code-point@1.0.0
  │   │ └── number-is-nan@1.0.1
  │   └─┬ strip-ansi@3.0.1
  │     └── ansi-regex@2.1.1
  ├── colors@1.1.2
  ├─┬ commander@2.9.0
  │ └── graceful-readlink@1.0.1
  ├── currency-symbol-map@3.1.0
  ├── immutable@3.8.1
  ├─┬ node-emoji@1.4.3
  │ └── string.prototype.codepointat@0.2.0
  └─┬ uber-client@0.0.1
    ├── dotenv@2.0.0
    ├── enumify@1.0.4
    ├── UNMET PEER DEPENDENCY request@^2.34
    └─┬ request-promise@4.1.1
      ├── bluebird@3.4.7
      ├── UNMET PEER DEPENDENCY request@^2.34
      ├─┬ request-promise-core@1.1.1
      │ └── lodash@4.17.4
      └── stealthy-require@1.0.0

npm WARN request-promise@4.1.1 requires a peer of request@^2.34 but none was installed.
npm WARN request-promise-core@1.1.1 requires a peer of request@^2.34 but none was installed.

$ uber time '1234 oak st, sf ca'

###
### The "request" library is not installed automatically anymore.
### But required by "request-promise".
###
### npm install request --save
###

/Users/dylan/n/lib/node_modules/uber-cli/node_modules/request-promise/lib/rp.js:20
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /Users/dylan/n/lib/node_modules/uber-cli/node_modules/request-promise/lib/rp.js:11:16
    at module.exports (/Users/dylan/n/lib/node_modules/uber-cli/node_modules/stealthy-require/lib/index.js:36:23)
    at Object.<anonymous> (/Users/dylan/n/lib/node_modules/uber-cli/node_modules/request-promise/lib/rp.js:10:19)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/dylan/n/lib/node_modules/uber-cli/node_modules/uber-client/build/UberClient.js:10:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
```

**Comment by alexperezpaya** [comment]
Same here :(

**Comment by jamesrom** [comment]
+1

**Comment by sotojuan** [comment]
`request` is also pretty bloated too, so maybe a good opportunity to switch to something else :-)

**Comment by aterribili** [comment]
`npm install request -g` solved for me (:

**Comment by jaebradley** [comment]
Yeah, I believe the issue is with [uber-client](https://github.com/jaebradley/uber-client), in particular  [uber-client#6](https://github.com/jaebradley/uber-client/pull/6). Could be related to the package requirements for the current version - will continue investigating.

**Comment by jaebradley** [comment]
@dylanpyle [this commit](https://github.com/jaebradley/uber-cli/commit/38bdeff0b9631fbd4e60f7e8a94b3eeb7b63f0fc) plus my recent update to the `uber-cli` npm package should solve the `request` problem. Let me know if you're still seeing issues.

![image](https://cloud.githubusercontent.com/assets/8136030/23287570/3b08c3e6-fa0c-11e6-8678-6d5fbbafe181.png)

**Comment by dylanpyle** [comment]
@jaebradley Thanks — I'm now seeing this:

```
$ uber price '1234 oak, sf ca'
Could not get price estimates
```

Also worth noting that the `-V` flag seems to be broken; it's reporting 0.0.1 even though I'm on 0.0.2

**Comment by jaebradley** [comment]
@dylanpyle well [the `price` command takes a `start` and an `end` ](https://camo.githubusercontent.com/cdcef2f7cc97222d828510f908ad0fc5ebeecc46/687474703a2f2f696d6775722e636f6d2f32514c4a4353772e706e67). I assume what you were looking for were time estimates? 

Which seem to work for me
![image](https://cloud.githubusercontent.com/assets/8136030/23290000/abe6c676-fa1b-11e6-862e-b67a3454b554.png)

Could you be more specific about how/when the `-V` flag is broken? `npm view uber-cli version` seems to return the right version for me.

**Comment by dylanpyle** [comment]
Ha! That explains it. Yes, requests work now. Thanks for the quick fix!

Will open a new issue for the version thing.
